---
# - name: remove rabbitmq users
#   rabbitmq_user:
#     user: "{{ item }}"
#     state: absent
#   with_items: "{{ rabbitmq_users_absent }}"

# - name: remove guest user
#   shell: |
#     rabbitmqctl delete_user guest

# - name: add admin user
#   shell: |
#     rabbitmqctl add_user admin ${admin_password}
#     rabbitmqctl set_user_tags admin administrator
#     rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"
